create table roles(
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name text unique not null
 );
commit ;

create table users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    surname text not null,
    patronymic text not null,
    username text unique not null,
    email text,
    password text not null ,
    role_id int references roles(id) not null,
    is_deleted boolean default false
);




insert into roles(name) values('ROLE_ADMIN');
insert into roles(name) values('ROLE_USER');
commit;

create table event
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    start timestamp NOT NULL,
    "end" timestamp NOT NULL,
    completed boolean default false,
    description text
);
commit;

create table file
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int references event(id) not null,
    original_name text not null,
    fs_name text not null,
    extension text,
    path text not null,
    is_deleted boolean default false

);
commit;
